# This file should compile into `dist/index.html`
template = "index.pug"

title = "Goodbye"
headline = "inlinemd:A beautiful headline with _italic_ content"
content = """md:
## A sub headline

__Very__ informative text
"""
